### ISSUE TITLE
Append option to run downstream dags or not in Coatue Task UI

### ISSUE THREAD

**Issue by skim-coatue** [coatue/airflow#170] opened 2019-12-02 23:17 UTC
- [ ] Add [checkbox](https://github.com/coatue/airflow/pull/152#pullrequestreview-325756286) for rerunning a task
- [ ] Make `Trigger DAG` from the DAG screen take the user to Dynamic Runs

**Comment by pathikrit** [comment] 2019-12-06 00:19
Dupe of #152

**Closed by pathikrit** 2019-12-06 00:19 UTC
